Fixed VPS -> VE, beginning of licensing change.

diff --git a/cache-os b/cache-os
--- a/cache-os
+++ b/cache-os
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Id: cache-os,v 1.14 2005/10/27 11:04:21 kir Exp $
+# $Id: cache-os,v 1.15 2006/05/11 14:20:35 kir Exp $
 #
 # Copyright (C) 2003, 2004, 2005 by SWsoft. Licensed under QPL.
 #
@@ -22,9 +22,9 @@ function usage()
 	exit 0
 }
 
-# Kills/umounts/destroys VPS.
+# Kills/umounts/destroys VE.
 # Parameters:
-#  $1 - VPS ID
+#  $1 - VE ID
 function cleanup()
 {
 	local vps=$1
@@ -87,15 +87,15 @@ if test "x$REMOVE" != "x"; then
 	exit 0
 fi
 
-VEID=`find_lock_nearest_veid 100000` || abort "Can't find free VPS ID"
-log4 "Using temporary VPS $VEID"
+VEID=`find_lock_nearest_veid 100000` || abort "Can't find free VE ID"
+log4 "Using temporary VE $VEID"
 VE_PRIVATE=`get_vz_var VE_PRIVATE`
 VE_ROOT=`get_vz_var VE_ROOT`
 
 
 VECFG=$VECFGDIR/$VEID.conf
 VECFGSAMPLE=$VECFGDIR/ve-vps.basic.conf-sample
-# simple init - for initial VPS startup, statically linked
+# simple init - for initial VE startup, statically linked
 MYINIT=${TOOLDIR}/myinit.${OSARCH}
 
 function terminate()
@@ -106,12 +106,12 @@ function terminate()
 trap terminate EXIT
 
 set -u
-cp -f $VECFGSAMPLE $VECFG || abort "Can't copy VPS config"
+cp -f $VECFGSAMPLE $VECFG || abort "Can't copy VE config"
 echo "DISK_QUOTA=no" >> $VECFG
 echo "OSTEMPLATE=$OSTEMPLATE" >> $VECFG
-mkdir -p $VE_ROOT $VE_PRIVATE || abort "Can't create VPS dirs"
-log4 Mounting VPS private area
-$VZCTL mount $VEID || abort "Can't mount VPS $VEID"
+mkdir -p $VE_ROOT $VE_PRIVATE || abort "Can't create VE dirs"
+log4 Mounting VE private area
+$VZCTL mount $VEID || abort "Can't mount VE $VEID"
 
 test -f $CACHEDIR/$CACHE && log4 "File $CACHEDIR/$CACHE exists"
 
@@ -129,9 +129,9 @@ if test -f $CACHEDIR/$CACHE -a "x$FORCE" = "x"; then
 	export VE_PRVT=$VE_PRIVATE
 	export PRIVATE_TEMPLATE=$CACHEDIR/$CACHE
 	$VZLIB_SCRIPTDIR/vps-create || \
-		abort "Failed to create a VPS based on cache $CACHE"
+		abort "Failed to create a VE based on cache $CACHE"
 	# Check if updates are available
-	# We use $YUM not vzyum here as latter requires VPS to be running
+	# We use $YUM not vzyum here as latter requires VE to be running
 	$YUM --installroot $VE_ROOT $YUM_CONF_FILE \
 		--vps=$VEID check-update
 	YUMEC=$?
@@ -146,10 +146,10 @@ if test -f $CACHEDIR/$CACHE -a "x$FORCE" = "x"; then
 else
 	log3 "Creating cache for $OSTEMPLATE OS template"
 	OPERATION="install"
-	# Fake init placed in order for VPS to be able to start
+	# Fake init placed in order for VE to be able to start
 	mkdir $VE_ROOT/sbin || abort "Can't create dir $VE_ROOT/sbin"
 	cp -f $MYINIT $VE_ROOT/sbin/init || \
-		abort "Unable to copy $MYINIT to VPS root ($VE_ROOT)"
+		abort "Unable to copy $MYINIT to VE root ($VE_ROOT)"
 	mkdir $VE_ROOT/proc || abort "Can't create dir $VE_ROOT/proc"
 fi
 
@@ -158,9 +158,9 @@ fi
 call_template_script $TDIR $OPERATION-pre || \
 	abort "Script $OPERATION-pre failed"
 
-# Start VPS now
-log4 Starting VPS
-$VZCTL start $VEID || abort "Can't start VPS $VEID"
+# Start VE now
+log4 Starting VE
+$VZCTL start $VEID || abort "Can't start VE $VEID"
 
 
 # install packages
@@ -194,13 +194,13 @@ unset XX_HOME
 call_template_script $TDIR $OPERATION-post || \
 	abort "Script $OPERATION-post failed"
 
-# Stop this VPS
-log4 Stopping VPS
+# Stop this VE
+log4 Stopping VE
 $VZCTL stop $VEID --fast
 log4 vzctl exit code $?
 
-# Umount VPS
-log4 Unmounting VPS
+# Umount VE
+log4 Unmounting VE
 $VZCTL umount $VEID
 log4 vzctl exit code $?
 
@@ -219,7 +219,7 @@ CACHESIZE=`ls -lh $CACHEDIR/$CACHE | awk '{print $5}'`
 log3 "Cache file $CACHE [$CACHESIZE] created."
 popd > /dev/null
 
-log4 Destroying VPS
+log4 Destroying VE
 $VZCTL destroy $VEID
 log4 vzctl exit code $?
 log4 rm -f $VECFGDIR/$VEID.*
diff --git a/vzrpm b/vzrpm
--- a/vzrpm
+++ b/vzrpm
@@ -1,9 +1,9 @@
 #!/bin/bash
-# $Id: vzrpm,v 1.9 2005/10/26 11:34:56 kir Exp $
+# $Id: vzrpm,v 1.10 2006/05/11 14:20:35 kir Exp $
 #
-# vzrpm - a wrapper for rpm to use rpm for OpenVZ VPS.
+# vzrpm - a wrapper for rpm to use rpm for OpenVZ VE.
 #
-# Copyright (C) 2005, SWsoft. Licensed under QPL.
+# Copyright (C) 2005, SWsoft. Licensed under GNU GPL v.2.
 # By Kir Kolyshkin.
 
 TOOLDIR=/usr/share/vzpkg
@@ -17,7 +17,7 @@ set -e
 
 function usage() {
 	cat << USAGE_EOF 1>&2
-Usage: $PROGNAME <VPSID> <arguments>
+Usage: $PROGNAME <VEID> <arguments>
   where <arguments> are yum arguments.
 USAGE_EOF
 	exit $1
@@ -32,14 +32,14 @@ get_veid $1
 shift
 USER_ARGS=$*
 # Sanity checks
-STATUS=`$VZCTL status $VEID` || abort "Can't get status for VPS $VEID: " \
+STATUS=`$VZCTL status $VEID` || abort "Can't get status for VE $VEID: " \
 	"vzctl status failed with code $?"
-echo $STATUS | grep -qw "exist" || abort "VPS $VEID not exist!"
-echo $STATUS | grep -qw "running" || abort "VPS $VEID not running; " \
+echo $STATUS | grep -qw "exist" || abort "VE $VEID not exist!"
+echo $STATUS | grep -qw "running" || abort "VE $VEID not running; " \
 	"you should start it first"
 RPM_ARGS="--root $VE_ROOT --veid $VEID"
 # Find out which RPM binary to use
-get_ve_os_template $VEID || abort "Can't get OSTEMPLATE for VPS $VEID"
+get_ve_os_template $VEID || abort "Can't get OSTEMPLATE for VE $VEID"
 TEMPLATE=`get_vz_var TEMPLATE`
 OST=`ost2full $OSTEMPLATE` || abort "No such OS template: $OSTEMPLATE"
 set $OST
