New vzpkg implementation
    This is the initial version of the rewritten vzpkg which is no
    long yum/rpm specific.

    This version supports both yum/rpm and Debian debootstrap/apt-get.

diff --git a/cache-os b/cache-os
--- a/cache-os
+++ b/cache-os
@@ -1,16 +1,41 @@
 #!/bin/bash
+# vim: ts=4 sw=4 ai noet
 # $Id: cache-os,v 1.18 2006/05/11 14:38:18 kir Exp $
 #
 # Copyright (C) 2003, 2004, 2005, 2006 by SWsoft. Licensed under GNU GPL.
 #
 # Creates/updates OS template cache.
+#
+# All scripts called by this script inherit the following environment variables:
+#
+# VZCTL
+#
+# OS_NAME
+# OS_VER
+# OS_ARCH
+# OS_SET
+#
+# TEMPLATE_DIR
+#
+# VEID
+# VE_PRIVATE
+# VE_ROOT
+#
+# In addition template scripts inherit the following functions:
+#
+# find_template_config_file
+#
 
-#DEBUG_LEVEL=5
+test -n "$DEBUG_EXEC" && set -x
+
 TOOLDIR=/usr/share/vzpkg
 
-
 . ${TOOLDIR}/functions
+
+export -f find_template_config_file
+
 VZCTL="$VZCTL --quiet --skiplock"
+export VZCTL
 
 log4 Started $0 $*
 
@@ -29,6 +54,7 @@ function cleanup()
 {
 	local vps=$1
 	log4 "Called cleanup($vps)"
+
 	log4 "Calling vzctl stop $vps"
 	$VZCTL stop $vps --fast
 	log4 "Calling vzctl umount $vps"
@@ -65,26 +91,30 @@ TEMPLATE=`get_vz_var TEMPLATE`
 
 OST=`ost2full $1` || abort "No such OS template: $1"
 set $OST
-OSNAME=$1
-OSVER=$2
-OSSET=$3
-OSARCH=$4
-TDIR=$5
-check_ost_exists $OSNAME $OSVER $OSSET $OSARCH || exit 1
+OS_NAME=$1
+OS_VER=$2
+OS_SET=$3
+OS_ARCH=$4
+TEMPLATE_DIR=$5
+check_ost_exists $OS_NAME $OS_VER $OS_SET $OS_ARCH || exit 1
 
-OSTEMPLATE="$OSNAME-$OSVER-$OSARCH-$OSSET"
-CACHE=$OSTEMPLATE.tar.gz
+OS_TEMPLATE="$OS_NAME-$OS_VER-$OS_ARCH-$OS_SET"
+
+export OS_NAME OS_VER OS_ARCH OS_SET
+export TEMPLATE_DIR
+
+CACHE=$OS_TEMPLATE.tar.gz
 CACHEDIR=`get_cache_dir`
-MARK64=`is_64bit $OSARCH`
+PACKAGER=`get_packager` || exit $?
 
-if test "x$REMOVE" != "x"; then
-	log3 "Removing OS template cache for $OSTEMPLATE template"
+if test "$REMOVE" != ""; then
+	log3 "Removing OS template cache for $OS_TEMPLATE template"
 	log4 "Cache file name: $CACHEDIR/$CACHE"
-	test -f $CACHEDIR/$CACHE || \
+	test -f "$CACHEDIR/$CACHE" || \
 		log2 "Cache file $CACHEDIR/$CACHE is not found!"
 	rm -f $CACHEDIR/$CACHE
 	# If there is a symlink (for older vzctl) remove it as well
-	test -L $TEMPLATE/$CACHE && rm -f $TEMPLATE/$CACHE
+	test -L "$TEMPLATE/$CACHE" && rm -f $TEMPLATE/$CACHE
 	exit 0
 fi
 
@@ -92,16 +122,21 @@ VEID=`find_lock_nearest_veid 100000` || abort "Can't find free VE ID"
 log4 "Using temporary VE $VEID"
 VE_PRIVATE=`get_vz_var VE_PRIVATE`
 VE_ROOT=`get_vz_var VE_ROOT`
-
+export VEID VE_PRIVATE VE_ROOT
 
 VECFG=$VECFGDIR/$VEID.conf
 VECFGSAMPLE=$VECFGDIR/ve-vps.basic.conf-sample
 # simple init - for initial VE startup, statically linked
-MYINIT=${TOOLDIR}/myinit.${OSARCH}
+case ${OS_ARCH} in
+i?86|x86)		MYINIT=${TOOLDIR}/myinit.i386;;
+amd64|x86_64)	MYINIT=${TOOLDIR}/myinit.x86_64;;
+ia64)			MYINIT=${TOOLDIR}/myinit.ia64;;
+*)				MYINIT=${TOOLDIR}/myinit.i386;;
+esac
 
 function terminate()
 {
-	log4 "\ncalling cleanup()"
+	log4 "Calling cleanup()"
 	cleanup $VEID
 }
 trap terminate EXIT
@@ -109,50 +144,36 @@ trap terminate EXIT
 set -u
 cp -f $VECFGSAMPLE $VECFG || abort "Can't copy VE config"
 echo "DISK_QUOTA=no" >> $VECFG
-echo "OSTEMPLATE=$OSTEMPLATE" >> $VECFG
+echo "OSTEMPLATE=$OS_TEMPLATE" >> $VECFG
 mkdir -p $VE_ROOT $VE_PRIVATE || abort "Can't create VE dirs"
 log4 Mounting VE private area
 $VZCTL mount $VEID || abort "Can't mount VE $VEID"
 
-test -f $CACHEDIR/$CACHE && log4 "File $CACHEDIR/$CACHE exists"
-
-# Set up PYTHONPATH for our vzyum
-PYTHONPATH=`get_rpm_pythonhome $TDIR`
-export PYTHONPATH
-log4 PYTHONPATH=$PYTHONPATH
-# Set LD_LIBRARY_PATH to access rpm libs
-set +u
-LD_LIBRARY_PATH=`get_rpmlib_path $TDIR`:$LD_LIBRARY_PATH
-set -u
-export LD_LIBRARY_PATH
-log4 LD_LIBRARY_PATH=$LD_LIBRARY_PATH
-
-YUM_CONF_FILE=`yum_conf $TDIR`
+test -f "$CACHEDIR/$CACHE" && log4 "File $CACHEDIR/$CACHE exists"
 
 # Check if we are going to update cache
-if test -f $CACHEDIR/$CACHE -a "x$FORCE" = "x"; then
-	log3 "Updating cache for $OSTEMPLATE OS template"
+if test -f "$CACHEDIR/$CACHE" -a "x$FORCE" = "x"; then
+	log3 "Updating cache for $OS_TEMPLATE OS template"
 	OPERATION="update"
 	log4 "Untarring $CACHEDIR/$CACHE"
-	export VE_PRVT=$VE_PRIVATE
-	export PRIVATE_TEMPLATE=$CACHEDIR/$CACHE
-	$VZLIB_SCRIPTDIR/vps-create || \
+	VE_PRVT=$VE_PRIVATE PRIVATE_TEMPLATE=$CACHEDIR/$CACHE $VZLIB_SCRIPTDIR/vps-create || \
 		abort "Failed to create a VE based on cache $CACHE"
 	# Check if updates are available
-	# We use $YUM not vzyum here as latter requires VE to be running
-	$YUM --installroot $VE_ROOT $YUM_CONF_FILE \
-		--vps=$VEID check-update
-	YUMEC=$?
-	if test $YUMEC -eq 0; then
+	script=$TOOLDIR/$PACKAGER-checkupdate
+	test -x "$script" || \
+		abort "Failed to find $script script"
+	$script
+	rc=$?
+	if test $rc -eq 0; then
 		log3 "No updates are available"
 		exit 0
-	elif test $YUMEC -eq 100; then
-		log3 "Updates are available - proceeding with update"
+	elif test $rc -eq 1; then
+		log3 "Updates may be available - proceeding with update"
 	else
-		abort "Command yum check-update failed with $YUMEC exit code"
+		abort "Command $script failed with $rc exit code"
 	fi
 else
-	log3 "Creating cache for $OSTEMPLATE OS template"
+	log3 "Creating cache for $OS_TEMPLATE OS template"
 	OPERATION="install"
 	# Fake init placed in order for VE to be able to start
 	mkdir $VE_ROOT/sbin || abort "Can't create dir $VE_ROOT/sbin"
@@ -161,45 +182,20 @@ else
 	mkdir $VE_ROOT/proc || abort "Can't create dir $VE_ROOT/proc"
 fi
 
-
 # Run setup-pre script
-call_template_script $TDIR $OPERATION-pre || \
+call_template_script $OPERATION-pre || \
 	abort "Script $OPERATION-pre failed"
 
 # Start VE now
 log4 Starting VE
 $VZCTL start $VEID || abort "Can't start VE $VEID"
 
+script=$TOOLDIR/$PACKAGER-$OPERATION
+test -x "$script" || abort "Failed to find $script script"
+$script || \
+	abort "Script $script failed"
 
-# install packages
-if test $OPERATION = 'install'; then
-	LIST=`get_packages $TDIR $OSSET`
-	YUM_CMD="install $LIST"
-	# install gpg keys
-	import_gpgkeys $TDIR
-elif test $OPERATION = 'update'; then
-	YUM_CMD="update"
-else
-	# this shouldn't happen
-	abort "Internal error: unknown OPERATION $OPERATION"
-fi
-
-# Dirty dirty hack for yum/rpm to read RPM macros from the file .rpmmacros
-# which resides in our template configuration directory. If you know a better
-# way of doing it, please enlighten me.
-XX_HOME=$HOME
-export HOME=$TDIR/config
-
-YUM_CMD="--installroot=$VE_ROOT --vps=$VEID $YUM_CONF_FILE -y $YUM_CMD"
-# -d $DEBUG_LEVEL
-log4 "Running $YUM $YUM_CMD"
-# FIXME1: We use $YUM not vzyum because latter requires OSTEMPLATE to be set.
-# FIXME2: We do set OSTEMPLATE, so what's the problem? Need to find out.
-$YUM $YUM_CMD || abort "yum failed with $? exit code"
-export HOME=$XX_HOME
-unset XX_HOME
-
-call_template_script $TDIR $OPERATION-post || \
+call_template_script $OPERATION-post || \
 	abort "Script $OPERATION-post failed"
 
 # Stop this VE
@@ -217,9 +213,7 @@ pushd $VE_PRIVATE > /dev/null
 log3 "Packing cache file $CACHE ... "
 mkdir -p $CACHEDIR
 tar --numeric-owner --exclude $CACHE -zcf $CACHE . || abort "tar failed"
-#pwd
-#ls -lh
-test -f $CACHEDIR/$CACHE && mv $CACHEDIR/$CACHE $CACHEDIR/$CACHE-old
+test -f "$CACHEDIR/$CACHE" && mv $CACHEDIR/$CACHE $CACHEDIR/$CACHE-old
 mv $CACHE $CACHEDIR
 
 CACHESIZE=`ls -lh $CACHEDIR/$CACHE | awk '{print $5}'`
diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,4 +1,5 @@
 #!/bin/bash
+# vim: ts=4 sw=4 ai noet
 # $Id: functions,v 1.24 2006/05/11 14:28:35 kir Exp $
 #
 # Copyright (C) 2004, 2005, 2006, SWsoft. Licensed under GNU GPL v.2.
@@ -13,21 +14,20 @@ test -z "$VZP_LOGFILE"	&& VZP_LOGFILE=/var/log/vzpkg.log
 test -z "$DEBUG_LEVEL"	&& DEBUG_LEVEL=3
 
 # Some handy definitions
-VZCTL=/usr/sbin/vzctl
+test -z "$VZCTL" && VZCTL=/usr/sbin/vzctl
 VZLOCKDIR=/vz/lock
-VECFGDIR_OLD=/etc/sysconfig/vz-scripts/
+VECFGDIR_OLD=/etc/sysconfig/vz-scripts
 VZCFG_OLD=/etc/sysconfig/vz
-VECFGDIR=/etc/vz/conf/
+VECFGDIR=/etc/vz/conf
 VZCFG=/etc/vz/vz.conf
 VZLIB_SCRIPTDIR=/usr/lib/vzctl/scripts
-YUM=/usr/share/vzyum/bin/yum
-ARCHES="i386 x86_64 ia64 x86"
+ARCHES="i386 i586 i686 amd64 x86_64 ia64 x86"
 
 # check that configs are in right place - use old values otherwise
-if ! test -d "$VECFGDIR"; then
+if test ! -d "$VECFGDIR"; then
 	VECFGDIR=$VECFGDIR_OLD
 fi
-if ! test -f "$VZCFG"; then
+if test ! -f "$VZCFG"; then
 	VZCFG=$VZCFG_OLD
 fi
 
@@ -95,29 +95,49 @@ function abort()
 	exit 1
 }
 
+# Finds a file or directory in the template config directory.
+# It looks first in the specified template directory for an 
+# architecture specific version, then up one level for an
+# OS version specific one, finally up two levels for the OS
+# default version.
+#
+# Parameters:
+#  $1 - config file name
+function find_template_config_file() 
+{ 
+	local file=$1
+	local result=""
+	if test -e $TEMPLATE_DIR/config/$file; then
+		result=$TEMPLATE_DIR/config/$file
+	elif test -e $TEMPLATE_DIR/../config/$file; then
+		result=$TEMPLATE_DIR/../config/$file
+	elif test -e $TEMPLATE_DIR/../../config/$file; then
+		result=$TEMPLATE_DIR/../../config/$file
+	fi
+	# Normalize path
+	if test -n "$result"; then
+		curdir=`pwd`
+		cd `dirname $result`
+		result=`pwd`/$file
+		cd $curdir
+		echo $result
+		return 0
+	else
+		return 1
+	fi
+}
+
 # Calls template-specific script to be run from host system (VE0)
 # Parameters:
-#  $1 - tdir
-#  $2 - script name
+#  $1 - script name
 function call_template_script()
 {
-	local tdir=$1
-	local script=$tdir/config/$2
-	if ! test -x $script; then
-		log4 "Script $script not found " \
-			"or non-exec: skipped"
+	local script=`find_template_config_file $1`
+	if ! test -x "$script"; then
+		log4 "Script $1 not found or non-exec: skipped"
 		return 0
 	fi
-	# Prepare script environment
-	set -u
-	export VE_ROOT
-	export VE_PRIVATE
-	export TEMPLATE
-	export BASEDIR
-	export VEID
-	export VZCTL
-	set +u
-	export RPM=`get_rpm $tdir`
+
 	log4 Calling script $script
 	# Run script
 	$script
@@ -130,29 +150,29 @@ function call_template_script()
 #  $1 - VE ID
 function lock_ve()
 {
-    local ntries=0 file=$VZLOCKDIR/$1.lck warned=0
-    while [ $ntries -le 3 ]; do
+	local ntries=0 file=$VZLOCKDIR/$1.lck warned=0
+	while [ $ntries -le 3 ]; do
 	ntries=$[ntries+1]
 	if lockfile -1 -r1 $file 2>/dev/null; then
-	    echo -e "$$\nupdating" >$file
-	    return
+		echo -e "$$\nupdating" >$file
+		return
 	else
-	    [ -f $file ] || abort "Cannot create $file lockfile"
-	    local pid=`cat $file 2>/dev/null`
-	    pid=`echo $pid | awk '{print $1}'`
-	    if [ "$pid" -a -e /proc/$pid/cmdline ]; then
+		[ -f $file ] || abort "Cannot create $file lockfile"
+		local pid=`cat $file 2>/dev/null`
+		pid=`echo $pid | awk '{print $1}'`
+		if [ "$pid" -a -e /proc/$pid/cmdline ]; then
 		if [ $warned -eq 0 ]; then
-		    log2 "VE $1 locked by pid=$pid"
-		    warned=1
+			log2 "VE $1 locked by pid=$pid"
+			warned=1
 		fi
 		continue
-	    else
+		else
 		log2 "Removing stale lockfile $file, pid=$pid"
 		rm -f $file
-	    fi
+		fi
 	fi
-    done
-    abort "Too many retries waiting for lockfile $file"
+	done
+	abort "Too many retries waiting for lockfile $file"
 }
 
 # Unlocks VE
@@ -160,32 +180,32 @@ function lock_ve()
 #  $1 - VE ID
 function unlock_ve()
 {
-    local file=$VZLOCKDIR/$1.lck
-#   log4 Unlocking VE $1
-    rm -f $file
+	local file=$VZLOCKDIR/$1.lck
+	# log4 Unlocking VE $1
+	rm -f $file
 }
 
 function lock_ve_silent()
 {
-    local ntries=0 file=$VZLOCKDIR/$1.lck
-    while [ $ntries -le 3 ]; do
+	local ntries=0 file=$VZLOCKDIR/$1.lck
+	while [ $ntries -le 3 ]; do
 	ntries=$[ntries+1]
 	if lockfile -1 -r1 $file 2>/dev/null; then
-	    echo -e "$$\nupdating" >$file
-	    return 0
+		echo -e "$$\nupdating" >$file
+		return 0
 	else
-	    [ -f $file ] || return 1
-	    local pid=`cat $file 2>/dev/null`
-	    pid=`echo $pid | awk '{print $1}'`
-	    if [ "$pid" -a -e /proc/$pid/cmdline ]; then
-	    	continue
-	    else
-		log2 "Removing stale lockfile $file, pid=$pid"
-		rm -f $file
-	    fi
+		[ -f $file ] || return 1
+		local pid=`cat $file 2>/dev/null`
+		pid=`echo $pid | awk '{print $1}'`
+		if [ "$pid" -a -e /proc/$pid/cmdline ]; then
+			continue
+		else
+			log2 "Removing stale lockfile $file, pid=$pid"
+			rm -f $file
+		fi
 	fi
-    done
-    return 1
+	done
+	return 1
 }
 
 
@@ -193,46 +213,46 @@ function lock_ve_silent()
 #
 function find_lock_nearest_veid()
 {
-    [ $# -eq 1 ] ||
-	abort "$FUNCNAME: usage $FUNCNAME OLD_VEID"
-    local old_veid=$1
+	[ $# -eq 1 ] ||
+		abort "$FUNCNAME: usage $FUNCNAME OLD_VEID"
+	local old_veid=$1
 
-    local veid=$old_veid
-    while ((++veid != old_veid)) ; do
-	[ -f $VECFGDIR/$veid.conf ] && continue
-    	lock_ve $veid
-	rc=$?
-   	[ $rc -eq 0 ] && {
-	    [ -f $VECFGDIR/$veid.conf ] && {
-		unlock_ve $veid
-		continue
-	    }
-	    local status
-	    status=`$VZCTL status $veid`
-	    # vzctl status should always return 0; if not, something is
-	    # really wrong (e.g. /dev/vzctl is missing).
-	    if test $? -ne 0; then
-		unlock_ve $veid
-		abort "$FUNCNAME: 'vzctl status' command returned" \
-			"non-zero exit code, which should not happen." \
-			"See /var/log/vzctl.log for details"
-	    fi
-	    echo "$status" | grep -q 'deleted unmounted down' || {
-		unlock_ve $veid
-		continue
-	    }
-	    # use get_vz_var since VE config file not exist
-	    local private=`VEID=$veid get_vz_var VE_PRIVATE`
-	    [ -e "$private" ] && {
-		unlock_ve $veid
-		continue
-	    }
-	    > $VECFGDIR/$veid.conf
-	    echo $veid
-	    return 0
-	}
-    done
-    return 1
+	local veid=$old_veid
+	while ((++veid != old_veid)) ; do
+		[ -f $VECFGDIR/$veid.conf ] && continue
+		lock_ve $veid
+		rc=$?
+		[ $rc -eq 0 ] && {
+			[ -f $VECFGDIR/$veid.conf ] && {
+				unlock_ve $veid
+				continue
+			}
+			local status
+			status=`$VZCTL status $veid`
+			# vzctl status should always return 0; if not, something is
+			# really wrong (e.g. /dev/vzctl is missing).
+			if test $? -ne 0; then
+				unlock_ve $veid
+				abort "$FUNCNAME: 'vzctl status' command returned" \
+					"non-zero exit code, which should not happen." \
+					"See /var/log/vzctl.log for details"
+			fi
+			echo "$status" | grep -q 'deleted unmounted down' || {
+				unlock_ve $veid
+				continue
+			}
+			# use get_vz_var since VE config file not exist
+			local private=`VEID=$veid get_vz_var VE_PRIVATE`
+			[ -e "$private" ] && {
+				unlock_ve $veid
+				continue
+			}
+			> $VECFGDIR/$veid.conf
+			echo $veid
+			return 0
+		}
+	done
+	return 1
 }
 
 # Returns requested variable from global VZ config file 
@@ -243,14 +263,14 @@ function get_vz_var()
 	# We have defaults for two most requested things
 	if test -z "$value"; then
 		case $1 in
-			PACKAGES)
-				value='/vz/packages'
-				;;
-			TEMPLATE)
-				value='/vz/template'
-				;;
-			*)
-				gotdef=0
+		PACKAGES)
+			value='/vz/packages'
+			;;
+		TEMPLATE)
+			value='/vz/template'
+			;;
+		*)
+			gotdef=0
 		esac
 		if test $gotdef -ne 0; then
 			log2 "Variable $1 not found in $VZCFG;" \
@@ -289,12 +309,12 @@ function get_arch() {
 	# so we have to use uname -m instead and convert the result.
 	local arch=`uname -m`
 	case $arch in
-		i?86)
-			echo i386
-			;;
-		*)
-			echo $arch
-			;;
+	i?86|x86)
+		echo i386
+		;;
+	*)
+		echo $arch
+		;;
 	esac
 }
 
@@ -389,27 +409,15 @@ function check_ost_exists()
 		log2 "No $osname-$osver OS template found for "\
 			"$osarch architecture"
 		return 1
-	elif ! test -f $template/$osname/$osver/$osarch/config/$osset.list; then
-		log2 "Set $osset for $osname-$osver-$osarch " \
-			"OS template not found"
-		return 1
+	else
+		local list_file=`find_template_config_file $osset.list`
+		if test ! -f $list_file; then
+			log2 "Set $osset for $osname-$osver-$osarch " \
+				"OS template not found"
+			return 1
+		fi
 	fi
 	return 0
-}
-
-# Returns list of packages to be installed into VE.
-# Parameters:
-#  $1 - TDIR
-#  $2 - OS SET
-function get_packages()
-{
-	local template=$TEMPLATE
-	[ -z "$template" ] && template=`get_vz_var TEMPLATE`
-	local tdir=$1
-	local osset=$2
-	local cfgdir=$tdir/config
-	local file=$cfgdir/${osset}.list
-	cat $file | egrep -v '^#|^[[:space:]]*$'
 }
 
 function get_ve_os_template()
@@ -422,47 +430,6 @@ function get_ve_os_template()
 		abort "VE $VEID can not be used with vzpkg utilities."
 	fi
 }
-
-# Returns -c parameters needed for yum.
-function yum_conf()
-{
-	local tdir=$1
-	local template=$TEMPLATE
-	if test -z "$template"; then
-		template=`get_vz_var TEMPLATE`
-	fi
-	local cfg=$tdir/config/yum.conf
-	# FIXME: check for osset-specific yum.conf
-	test -f $cfg || abort "yum repository config file " \
-		"($cfg) not found!"
-	echo "-c $cfg"
-}
-
-
-# Import gpgkeys from OS template's config/gpgkeys directory to the VE.
-# Parameters:
-#  $1 - template dir
-# Environment: VE_ROOT should be set.
-function import_gpgkeys()
-{
-	local tdir=$1
-	test -z "$tdir" && abort "$FUNCNAME: argument missing"
-	test -z "$VE_ROOT" && abort "$FUNCNAME: VE_ROOT not set"
-	local keydir=$tdir/config/gpgkeys
-	test -d $keydir || return
-	local file
-	local files=''
-	for file in $keydir/*; do
-		files="$files $file"
-	done
-	
-	if ! test -z "$files"; then
-		rpm=`get_rpm $tdir`
-		log4 "Importing RPM GPG keys: $files"
-		$rpm --root $VE_ROOT --import $files
-	fi
-}
-
 
 # Gets VE ID from command line argument
 function get_veid()
@@ -488,65 +455,34 @@ function get_all_os_templates() {
 	# Here we need it to be ended by slash
 	echo $template | egrep -q '/$' || template="${template}/"
 
-	# /vz/template/fedora-core/3/i386/config/default.list
-	local list=`find $template -maxdepth 5 -mindepth 5 \
-		-type f -name \*.list | \
-		egrep '/config/[^/]*\.list' | \
-		sed -e "s@^${template}@@" -e 's@/config@@' \
-			-e 's/.list$//' -e 's@/@-@g'`
+	local template_list=`(
+		ls $template/*/*/*/config/*.list 2> /dev/null
+		for path in $template/*/*/*/config
+		do
+		if [ -d $path ]; then
+			os_arch=\`dirname $path\`
+			os_version=\`dirname $os_arch\`
+			os_name=\`dirname $os_version\`
+			os_arch=\`basename $os_arch\`
+			os_version=\`basename $os_version\`
+			os_name=\`basename $os_name\`
+			for list in $template/$os_name/config/*.list $template/$os_name/$os_version/config/*.list
+			do
+				if [ -f $list ]; then
+					echo $os_name/$os_version/$os_arch/config/\`basename $list\`
+				fi
+			done
+		fi
+		done
+	) | sed -e "s;^${template}/;;" -e "s;/config;;" -e "s;\.list$;;" -e "s;/;-;g" | sort`
 
-	echo $list
+	echo $template_list
 }
 
-function get_pythonver() {
-	python -c 'import sys; v=sys.version_info; \
-		print "%d.%d" % (v[0], v[1])'
-}
-
-function get_rpm_path()
+function get_packager()
 {
-	local tdir=$1
-	[ -z "$tdir" ] && abort "$FUNCNAME: tdir argument missing"
-	local cfgdir=$tdir/config
-	local rpmf=$cfgdir/rpm
-	test -f $rpmf || abort "File $rpmf not found!"
-	local rpmver=`cat $rpmf`
-	local path=/usr/share/vzpkgtools/vzrpm${rpmver}
-	test -d $path || abort "vzrpm${rpmver} path not found: $path"
-	echo $path
-}
-
-function get_rpm()
-{
-	local rpm=`get_rpm_path $1`/bin/rpm
-	test -x $rpm || abort "RPM not found or non-executable: $rpm"
-	echo $rpm
-}
-
-function get_rpm_pythonhome()
-{
-	local pyver=`get_pythonver`
-	local path=`get_rpm_path $1`/lib${MARK64}/python${pyver}/site-packages
-	test -d $path || abort "RPM python path not found: $path"
-	echo $path
-}
-
-function get_rpmlib_path()
-{
-        local path=`get_rpm_path $1`/lib${MARK64}
-        test -d $path || abort "RPM lib path not found: $path"
-        echo $path
-}
-
-function is_64bit()
-{
-# Here we assume that all the architectures but i*86 are 64bit :)
-	case $1 in
-	i*86)
-		echo -n
-		;;
-	*)
-		echo -n 64
-		;;
-	esac
+	local packager_file=`find_template_config_file packager`
+	test -z "$packager_file" -o ! -f "$packager_file" && abort "File $packager_file not found!"
+	local packager=`cat $packager_file`
+	echo -n $packager
 }
diff --git a/vzpkgrm b/vzpkgrm
--- a/vzpkgrm
+++ b/vzpkgrm
@@ -1,7 +1,45 @@
 #!/bin/bash
-# $Id: vzpkgrm,v 1.3 2006/05/11 14:20:35 kir Exp $
-# Copyright (C) 2004, 2005, SWsoft. Licensed under GNU GPL v.2.
+# vim: ts=4 sw=4 ai noet
+# $Id$
+#
+# Copyright (C) 2008, Robert Nelson. Licensed under GPLv2.
+# By Robert Nelson.
+#
 
-VEID=$1
+test -n "$DEBUG_EXEC" && set -x
+
+TOOLDIR=/usr/share/vzpkg
+
+. ${TOOLDIR}/functions
+
+export -f find_template_config_file
+
+get_veid $1
+export VEID VE_ROOT VE_PRIVATE
+
 shift
-exec /usr/bin/vzrpm $VEID -e $*
+USER_ARGS=$*
+# Sanity checks
+STATUS=`$VZCTL status $VEID` || abort "Can't get status for VE $VEID: " \
+	"vzctl status failed with code $?"
+echo $STATUS | grep -qw "exist" || abort "VE $VEID not exist!"
+echo $STATUS | grep -qw "running" || abort "VE $VEID not running; " \
+	"you should start it first"
+
+get_ve_os_template $VEID || abort "Can't get OSTEMPLATE for VE $VEID"
+TEMPLATE=`get_vz_var TEMPLATE`
+OST=`ost2full $OSTEMPLATE` || abort "No such OS template: $OSTEMPLATE"
+set $OST
+OS_NAME=$1
+OS_VER=$2
+OS_SET=$3
+OS_ARCH=$4
+TEMPLATE_DIR=$5
+export OS_NAME OS_VER OS_SET OS_ARCH TEMPLATE_DIR
+check_ost_exists $OS_NAME $OS_VER $OS_SET $OS_ARCH || exit 1
+
+PACKAGER=`get_packager` || exit 1
+
+# Run it
+log4 exec $TOOLDIR/$PACKAGER-rm $USER_ARGS
+exec $TOOLDIR/$PACKAGER-rm $USER_ARGS
