Support for template flavors; vzrpmxx/vzyum support  - preliminary support for template 'flavours'  - support for different (per OSTEMPLATE) rpm versions  - support for customized yum

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Id: functions,v 1.12 2005/09/16 13:04:53 kir Exp $
+# $Id: functions,v 1.13 2005/09/29 14:33:33 kir Exp $
 #
 # Copyright (C) 2004, 2005, SWsoft. Licensed under QPL.
 # By Kir Kolyshkin.
@@ -18,6 +18,7 @@ VZLOCKDIR=/vz/lock
 VECFGDIR=/etc/sysconfig/vz-scripts/
 VZCFG=/etc/sysconfig/vz
 VZLIB_SCRIPTDIR=/usr/lib/vzctl/scripts
+YUM=/usr/share/vzyum/bin/yum
 
 
 # Handy functions
@@ -318,36 +319,21 @@ function check_veid()
 
 function name2basedir()
 {
-	echo $1 | sed 's#-\([^-]*\)$#/\1#'
+	echo $1 | sed -e 's/--.*$//' -e 's#-\([^-]*\)$#/\1#'
 }
 
-# Returns full name of template config file.
+# Extracts 'flavor' component of template name.
 # Parameters:
-#  $1 - OS template name (like "redhat-9")
-#  $2 - optional app template name (like "mysql")
-#  THISTEMPLATE - template base dir (should be set!)
-function get_tmpl_config()
+#  $1 - template name (like "fedora-core-3--min")
+# Returns:
+#  flavor (like "--min")
+function name2flavor()
 {
-	if test "x$THISTEMPLATE" == "x"; then
-		log1 "Internal error! THISTEMPLATE is undefined " \
-			"in call to get_tmpl_config. Aborting!"
-		exit 1
-	fi
 	local osname=$1
-	local basedir=`name2basedir $osname`
-	local cfgdir=$THISTEMPLATE/config
-	if test $# -eq 1; then
-		# OS template
-		local file=$cfgdir/ostemplate.conf
-		echo $file
-	elif test $# -eq 2; then
-		# App template
-		appname=$2
-		local file=$cfgdir/$appname/template.conf
-		echo $file
+	if ! echo $osname | fgrep -q -- '--'; then
+		echo -n
 	else
-		log1 "Internal error! get_tmpl_config requires 1 or 2 args!"
-		exit 1
+		echo $osname | sed 's/^.*\(--.*\)$/\1/'
 	fi
 }
 
@@ -368,7 +354,8 @@ function get_packages()
 	local cfgdir=$THISTEMPLATE/config
 	if test $# -eq 1; then
 		# OS template
-		local file=$cfgdir/ostemplate.list
+		local flavor=`name2flavor $osname`
+		local file=$cfgdir/ostemplate${flavor}.list
 		cat $file | egrep -v '^#|^[[:space:]]*$'
 	elif test $# -eq 2; then
 		# App template
@@ -390,29 +377,6 @@ function get_all_basedirs()
 	local basedirs=`find $packages -maxdepth 2 -mindepth 2 -type d \
 		-print | sed "s@^$packages[/]*@@"`
 	echo $basedirs
-}
-
-function get_all_ostemplates()
-{
-	local tdir pdir ost ret
-	local template=$TEMPLATE
-	local packages=$PACKAGES
-	if test -z "$template"; then
-		template=`get_vz_var TEMPLATE`
-	fi
-	if test -z "$packages"; then
-		packages=`get_vz_var PACKAGES`
-	fi
-	local pdirs=`find $packages -maxdepth 2 -mindepth 2 -type d -print`
-	for pdir in $pdirs; do
-		tdir=`echo $pdir | sed -e "s@^$packages@$template@"`
-		if test -f $tdir/config/ostemplate.conf; then
-			ost=`echo $tdir | sed -e "s@^$template[/]*@@" \
-				-e 's@/\([^/]*\)$@-\1@'`
-			ret="$ret $ost"
-		fi
-	done
-	echo $ret
 }
 
 
@@ -551,6 +515,37 @@ function check_ost_exist() {
 	local template=`get_vz_var TEMPLATE`
 	local thistemplate="$template/`name2basedir $1`"
 	local configdir=$thistemplate/config/
-	local pkglist=${configdir}ostemplate.list
+	local flavor=`name2flavor $1`
+	local pkglist=${configdir}ostemplate${flavor}.list
 	test -f $pkglist || abort "OS template $1 does not exist!"
+}
+
+function get_pythonver() {
+	python -c 'import sys; v=sys.version_info; \
+		print "%d.%d" % (v[0], v[1])'
+}
+
+function get_rpm_path()
+{
+	if test "x$THISTEMPLATE" == "x"; then
+		log1 "Internal error! THISTEMPLATE is undefined " \
+			"in call to $0. Aborting!"
+		exit 1
+	fi
+	local cfgdir=$THISTEMPLATE/config
+	local rpmf=$cfgdir/rpm
+	test -f $rpmf || abort "File $rpmf not found!"
+	local rpmver=`cat $rpmf`
+	echo /usr/share/vzpkgtools/vzrpm$rpmver
+}
+
+function get_rpm()
+{
+	echo `get_rpm_path`/bin/rpm
+}
+
+function get_rpm_pythonhome()
+{
+	local pyver=`get_pythonver`
+	echo `get_rpm_path`/lib/python${pyver}/site-packages
 }
